version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: news_aggregator
    ports:
      - 8000:8000
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=local
      - DB_CONNECTION=mysql
